//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPLOYEE_MANAGEMENT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_EMPLOYEESEntities : DbContext
    {
        public DB_EMPLOYEESEntities()
            : base("name=DB_EMPLOYEESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_logs> tbl_logs { get; set; }
        public virtual DbSet<tbl_employees> tbl_employees { get; set; }
    }
}
