//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPLOYEE_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_logs
    {
        public long log_id { get; set; }
        public Nullable<long> log_emp_id { get; set; }
        public string log_action { get; set; }
        public Nullable<long> log_action_by { get; set; }
    
        public virtual tbl_employees tbl_employees { get; set; }
        public virtual tbl_employees tbl_employees1 { get; set; }
    }
}
