//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPLOYEE_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_employees()
        {
            this.tbl_logs = new HashSet<tbl_logs>();
            this.tbl_logs1 = new HashSet<tbl_logs>();
        }
    
        public long emp_id { get; set; }
        public string emp_first_name { get; set; }
        public string emp_last_name { get; set; }
        public string emp_email { get; set; }
        public Nullable<System.DateTime> emp_dob { get; set; }
        public string emp_gender { get; set; }
        public string emp_password { get; set; }
        public Nullable<byte> emp_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_logs> tbl_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_logs> tbl_logs1 { get; set; }
    }
}
